# Generated by Django 2.0 on 2018-03-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/media/img/placeholder.jpeg', upload_to='img'),
        ),
    ]
